// ********RoostGPT********
/*
Test generated by RoostGPT for test dm-java-test-29 using AI Type Azure Open AI and AI Model roost-gpt4-32k

Test Scenario 1: Validate successful execution
Given the system is properly set up with dependencies 
When prodDatabaseConnection() is called
Then we verify the function executes without any exception.

Test Scenario 2: Validate the Output
Given the function prodDatabaseConnection() is executed 
When we verify its output 
Then it should match "DB Connection to RDS_PROD - High Performance Instance"

Test Scenario 3: Validate Console output
Given the function prodDatabaseConnection() is executed
When we check the console logs
Then it should print "DB Connection to RDS_PROD - High Performance Instance", driverClassName, and url in order

Test Scenario 4: Validate Driver Class Name
Given the function prodDatabaseConnection() is executed
When we check the printed driverClassName 
Then it should match the actual driver class used for making database connection 

Test Scenario 5: Validate URL
Given the function prodDatabaseConnection() is executed
When we check the printed url
Then it should match the actual database URL used for making the database connection

Note: Please ensure you have stubbed necessary methods to return expected values while executing these test scenarios.
*/

// ********RoostGPT********
mvn install:install-file -Dfile=<path-to-jar> -DgroupId=com.your.group -DartifactId=your-artifactId -Dversion=1.0.0 -Dpackaging=jar
